defaults:
  - basic
  - model: diffusion
  - data@train_dataloader.dataset.datasets: train
  - data@val_dataloader.dataset.datasets: val
  - _self_

exp_dir: experiments/waveform_vae_udit_diffusion/audiocaps/

sample_rate: 24000

train_dataloader:
  _target_: torchdata.stateful_dataloader.StatefulDataLoader
  dataset:
    _target_: data_module.dataset.AudioGenConcatDataset
  batch_size: 24 # per device batch size
  shuffle: True
  num_workers: 8
  collate_fn:
    _target_: data_module.collate_function.PaddingCollate
    pad_keys: ["waveform"]

val_dataloader:
  _target_: torch.utils.data.DataLoader
  dataset:
    _target_: data_module.dataset.AudioGenConcatDataset
  batch_size: 24 # per device batch size
  shuffle: False
  num_workers: 8
  collate_fn:
    _target_: data_module.collate_function.PaddingCollate
    pad_keys: ["waveform"]


loss_fn:
  _target_: torch.nn.Identity

trainer:
  _target_: audio_generation_trainer.AudioGenerationTrainer
  project_dir: ${exp_dir}
  logging_file: ${logging_file}
  gradient_accumulation_steps: ${gradient_accumulation_steps}
  epochs: ${epochs}
  epoch_length: ${epoch_length}
  save_last_k: 3
  wandb_config:
    _target_: trainer.WandbConfig
    project: x_to_audio_generation
    save_dir: ${exp_dir}
    name: audiocaps_waveform_vae_udit_diffusion
